name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 11 * * *'  # Körs varje dag 
  workflow_dispatch:  # Möjlighet att köra manuellt

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout forked repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/KelvinTegelaar/CIPP-API.git
          git fetch upstream
          git checkout master
          git merge upstream/master --ff-only
          git push origin master
